#!/usr/bin/python
# Floris Douw
# 2020
#
# AoC 2020 Day 3: Toboggan Trajectory

from math import prod


def count_trees(right, down):
    treecount = 0
    for i in range(0, len(data), down):
        if data[i][right * i % len(data[i])] == '#':
            treecount += 1
    return treecount


with open('input/day03', 'r') as f:
    data = [line.strip() for line in f]  # f.readlines() also copies the newlines


print(f'Part 1: {count_trees(3,1)}')
print(f'Part 2: {prod([count_trees(r,d) for r,d in [(1,1),(3,1),(5,1),(7,1),(1,2)]])}')
