#!/usr/bin/python
# Floris Douw
# 2020
#
# AoC 2020 Day 3: Toboggan Trajectory

with open('input/day03', 'r') as f:
    data = f.readlines()


def count_trees(right, down):
    treecount = 0
    for i in range(0, len(data), down):
        if data[i][right * i % len(data[i].strip())] == '#':
            treecount += 1
    return treecount


print(f'Part 1: {count_trees(3,1)}')

print(f'Part 2: {count_trees(1,1) * count_trees(3,1) * count_trees(5,1) * count_trees(7,1) * count_trees(1,2)}')
