#!/usr/bin/python
# Floris Douw
# 2020
#
# AoC 2020 Day 11: Seating System


def showgrid(grid):
    for y in range(len(grid)):
        print(''.join(grid[y]))
    print('')


def update(grid):
    tmp = [row.copy() for row in grid]
    changed = False
    for y in range(len(grid)):
        for x in range(len(grid[y])):
            if grid[y][x] == 'L':
                seatAvailable = True
                for i in range(max(0, y-1), min(y+2, len(grid))):
                    for j in range(max(0, x - 1), min(x + 2, len(grid[y]))):
                        if grid[i][j] == '#':
                            seatAvailable = False
                            break
                    if not seatAvailable:
                        break
                if seatAvailable:
                    changed = True
                    tmp[y][x] = '#'
            elif grid[y][x] == '#':
                count = 0
                for i in range(max(0, y-1), min(y+2, len(grid))):
                    for j in range(max(0, x - 1), min(x + 2, len(grid[y]))):
                        if grid[i][j] == '#':
                            count += 1
                if count >= 5:  # 4 adjacent + the seat itself
                    changed = True
                    tmp[y][x] = 'L'
    return changed, tmp


with open('input/day11') as f:
    grid = [[*(line.strip())] for line in f]
    changed = True
    bla = 0
    while changed:
        changed, grid = update(grid)
    count = 0
    for y in range(len(grid)):
        count += grid[y].count('#')
    print(f'Part 1: {count}')
