#!/usr/bin/python
# Floris Douw
# 2020
#
# AoC 2020 Day 21: Allergen Assessment

import re

with open('input/day21', 'r') as f:
    possible_allergens = {}
    all_ingredients = set()

    for line in f:
        # Collect possible ingredients for each allergen
        i, a = line.strip().strip(')').split(' (contains ')
        i = set(i.split(' '))
        all_ingredients = all_ingredients.union(i)
        for allergen in a.split(', '):
            if allergen in possible_allergens:
                possible_allergens[allergen] = possible_allergens[allergen].intersection(i)
            else:
                possible_allergens[allergen] = i

    # Further filter the list of possible allergens to uniquely matching ingredients
    allergens = {}
    while len(allergens) < len(possible_allergens):
        for a, iset in possible_allergens.items():
            if len(iset) == 1:
                for ingredient in iset:
                    break
                allergens[a] = ingredient
                for other in possible_allergens:
                    if ingredient in possible_allergens[other]:
                        possible_allergens[other].remove(ingredient)

    # Find ingredients that have no matches, count them in the full text
    safe = all_ingredients.difference(allergens.values())
    f.seek(0)
    text = f.read()
    safe_count = sum(len(re.findall(rf'\b{ingredient}\b', text)) for ingredient in safe)
    print(f'Part 1: {safe_count}')

    print(f"Part 2: {','.join(allergens[k] for k in sorted(allergens))}")
